"""Interview-question reference answers for ML/DL handwriting modules."""

from __future__ import annotations


MODULE_ANSWERS: dict[str, list[str]] = {
    "ml_dl_handwriting/00_math_primitives/euclidean_distance_matrix": [
        "可以利用恒等式 `||x-y||^2 = ||x||^2 + ||y||^2 - 2xy`，先分别算出 X 和 Y 的平方范数，再用矩阵乘法得到两两内积。时间复杂度仍是 `O(mnd)`，但避免显式构造 `[m,n,d]` 的差分张量，中间内存主要是输出矩阵 `O(mn)`。",
        "平方根是单调递增函数，所以比较距离大小时，平方距离和真实欧氏距离的排序完全一致。最近邻只关心谁更小，不关心距离的物理单位，因此省掉开方可以减少计算和数值误差。",
        "欧氏距离适合特征已经对齐、尺度有意义、向量范数也携带信息的场景，比如标准化后的连续特征。余弦相似度更关注方向，适合文本 embedding、语义向量这类范数容易受长度或置信度影响的表示。",
        "可以按 query 样本分块，逐块计算 `[block_size, n]` 的距离，再把结果写入输出或只保留 top-k。block size 由可用显存或内存决定，核心原则是不要同时物化完整 `[m,n,d]` 或过大的 `[m,n]` 临时矩阵。",
    ],
    "ml_dl_handwriting/00_math_primitives/softmax_stable": [
        "softmax 的分子分母都会同时乘上 `exp(-c)`，这个公共因子会被约掉，所以减去同一个常数不改变结果。通常取最大值作为 `c`，可以让最大的指数项变成 1，避免 `exp` 上溢。",
        "二分类时，两个 logits 的 softmax 可以化成对 logit 差值做 sigmoid，所以 sigmoid 可以看成二分类 softmax 的特例。多分类单标签场景用 softmax，因为类别之间互斥；多标签场景通常每个标签独立用 sigmoid。",
        "分开算 softmax 再取 log 容易遇到上溢、下溢和 `log(0)`。把 log-softmax 和 NLL 合并后可以用 log-sum-exp 稳定计算，同时避免保存不必要的中间概率。",
        "temperature 越小，logits 被放大，分布越尖锐，模型更偏向最大 logit。temperature 越大，分布越平滑，常用于蒸馏、采样多样性控制和校准分析。",
    ],
    "ml_dl_handwriting/00_math_primitives/cross_entropy": [
        "对 logits 求导时，softmax 的雅可比矩阵和 `-log p_y` 的梯度会合并，最终得到 `p - y`。这个结果直观上表示预测概率比目标概率高的类别要被压低，目标类别要被抬高。",
        "logits 可以进入 fused cross entropy，用 log-sum-exp 做稳定计算，避免先 softmax 后 log 的数值问题。如果输入已经是概率，极小概率会导致 `log(0)` 或梯度不稳定，而且还可能重复 softmax。",
        "label smoothing 会把 one-hot 目标改成“目标类接近 1、非目标类有少量概率”的软标签。这样梯度不再把正确类概率强推到 1，可以减轻过度自信，常对泛化和校准有帮助。",
        "可以给不同类别设置 class weight，让少数类样本的 loss 权重更大。工程上也常结合重采样、focal loss 或按业务成本设置权重，但要注意验证集指标是否真的改善。",
    ],
    "ml_dl_handwriting/00_math_primitives/mse_loss": [
        "MSE 对误差做平方，误差变大时惩罚是二次增长；MAE 是线性增长。异常值往往误差很大，所以在 MSE 下会主导 loss 和梯度。",
        "MSE 适合噪声接近高斯、希望大误差被更强惩罚的回归训练。RMSE 和原标签同量纲，便于解释；MAE 对异常值更稳健，适合重尾噪声或更关心绝对偏差的场景。",
        "分母要和 loss 的定义一致：如果 loss 是所有元素的 mean，梯度就除以元素总数；如果先按样本聚合再平均，就除以 batch size。面试里关键不是固定答案，而是 loss 数值和梯度尺度必须一致。",
        "Huber loss 在小误差区间使用平方惩罚，保持 MSE 的平滑梯度；在大误差区间切换成近似线性惩罚，降低异常值影响。阈值 delta 控制从 MSE 到 MAE 的切换点。",
    ],
    "ml_dl_handwriting/00_math_primitives/auc_binary": [
        "ROC-AUC 衡量正样本分数排在负样本前面的能力，不依赖某一个阈值，因此在类别比例变化时比 accuracy 稳定。它仍然有局限：极端不均衡时，很多负样本容易让 ROC 曲线看起来不错，但业务关心的 precision 可能很差。",
        "ROC-AUC 看的是 TPR 和 FPR 的权衡，PR-AUC 看的是 precision 和 recall 的权衡。极端不均衡时通常更关注 PR-AUC，因为少数类检出后到底有多少是真的，直接反映在 precision 上。",
        "AUC 可以解释为随机抽一个正样本和一个负样本，模型给正样本打分更高的概率，分数相等时通常按 0.5 计。这个解释说明 AUC 本质是排序指标，而不是概率校准指标。",
        "严格单调变换不会改变样本分数的相对顺序，所以 AUC 不变。非单调变换或大量制造 ties 会改变排序关系，AUC 才可能变化。",
    ],
    "ml_dl_handwriting/00_math_primitives/entropy_kl": [
        "交叉熵可以分解为 `H(p, q) = H(p) + KL(p||q)`。训练时如果真实分布 p 固定，最小化交叉熵等价于最小化模型分布 q 到 p 的 KL。",
        "KL 用来度量两个分布的差异，因此适合表达“学生模型贴近教师模型”或“新策略不要偏离参考策略”。它不是普通距离，但在蒸馏、RLHF/DPO、策略约束中能自然刻画分布层面的偏移。",
        "KL 非负来自 Gibbs inequality，本质上是真实分布下的 log 概率比期望不会小于 0。只有当两个分布在支持集上几乎处处相等时，KL 才等于 0。",
        "正向 KL `KL(p||q)` 更怕 q 漏掉 p 有质量的区域，因此倾向覆盖多个模式。反向 KL `KL(q||p)` 更怕 q 放到 p 很小的区域，因此更容易 mode-seeking，只贴一个高密度模式。",
    ],
    "ml_dl_handwriting/00_math_primitives/pca_first_component": [
        "第一主成分是在单位长度约束下最大化投影方差的方向，也就是最大化 `v^T C v`。根据 Rayleigh quotient，这个最大值由协方差矩阵最大特征值对应的特征向量取得。",
        "中心化后的数据矩阵做 SVD：`X = U S V^T`，右奇异向量 V 就是特征空间的主成分方向。协方差矩阵 `X^T X / n` 的特征值与奇异值平方成比例，所以 PCA 可以通过 SVD 稳定实现。",
        "PCA 是无监督方法，只使用特征矩阵的方差结构，不使用标签。它找到的是最大方差方向，不一定是最有分类或预测能力的方向。",
        "常见做法是看累计解释方差比，比如保留 90% 或 95% 方差。也可以结合下游验证集表现、可视化需求或计算预算来选维度，而不是只靠一个固定阈值。",
    ],
    "ml_dl_handwriting/01_classical_ml/knn_classifier": [
        "KNN 几乎没有显式训练过程，朴素实现的训练复杂度接近存储训练集的 `O(nd)`。预测一个样本需要和所有训练样本算距离，复杂度是 `O(nd)`，预测 m 个样本就是 `O(mnd)`。",
        "K 太小会对噪声和离群点敏感，决策边界很抖；K 太大会过度平滑，少数类和局部结构容易被多数邻居淹没。通常通过交叉验证选择 K，并配合标准化和合适的距离度量。",
        "低维空间可以用 KDTree 或 BallTree 做精确或近似加速。高维 embedding 场景更常用 ANN 方法，比如 HNSW、IVF、PQ，用少量召回损失换取查询速度和内存效率。",
        "维度升高后，样本间距离会趋于相近，最近邻和普通邻居的区分度下降。与此同时，覆盖高维空间需要指数级更多样本，所以 KNN 的局部投票假设会变弱。",
    ],
    "ml_dl_handwriting/01_classical_ml/kmeans_one_step": [
        "assignment 固定中心，把每个样本分到最近的簇；update 固定分配，用簇内均值更新中心。两步交替分别优化同一个平方误差目标中的不同变量。",
        "KMeans 对初始中心很敏感，因为目标函数非凸，初始化不同可能落到不同局部最优。KMeans++ 倾向选择彼此较远的初始中心，降低坏初始化概率，加快收敛。",
        "肘部法看 inertia 随 K 增加的下降曲线，在收益明显变小的拐点选 K。silhouette score 同时看簇内紧密和簇间分离，越高通常表示聚类结构越清晰。",
        "可以用矩阵化距离、分块计算、近似最近中心搜索来加速 assignment。数据很大时常用 mini-batch KMeans，每次只用小批样本更新中心，用更低成本逼近全量结果。",
    ],
    "ml_dl_handwriting/01_classical_ml/kmeans_full": [
        "KMeans 的目标函数对簇分配和中心同时优化时是非凸的，交替优化只能保证每一步不增大目标。它会收敛到某个稳定分配，但这个点不一定是全局最优。",
        "KMeans++ 第一步随机选中心，之后按到已有中心的距离平方加权采样新中心。直觉是让初始中心分散覆盖数据空间，减少多个中心挤在同一簇附近的情况。",
        "KMeans 假设簇大致是凸的、球状的、方差接近的结构。非凸簇、不同密度簇或强噪声数据会让“离均值最近”这个准则失效，DBSCAN 或谱聚类可能更合适。",
        "KMeans 用硬分配和均值中心，适合球状簇；GMM 用软分配和概率分布，可以表达椭圆形簇；DBSCAN 基于密度连接，可以发现任意形状簇并标记噪声。",
    ],
    "ml_dl_handwriting/01_classical_ml/linear_regression_gd": [
        "无正则且 `X^T X` 可逆时，闭式解是 `w = (X^T X)^(-1) X^T y`。特征维很高、样本很多、矩阵病态或需要在线训练时，直接求逆代价高且数值不稳，更适合 GD 或正则化解法。",
        "GD 每次用全量数据算梯度，方向稳定但单步成本高。SGD 每次用单样本，噪声大但更新快；mini-batch SGD 在稳定性和计算效率之间折中，是深度学习里最常用的形式。",
        "特征尺度差异大时，损失曲面会很狭长，梯度下降在不同方向上的合适步长差别很大。标准化后曲面更接近各向同性，同一个学习率更容易稳定快速收敛。",
        "L2 正则会惩罚权重平方，使解更平滑、权重更小，通常不会产生严格稀疏。L1 正则惩罚绝对值，容易把部分权重压到 0，因此有特征选择效果。",
    ],
    "ml_dl_handwriting/01_classical_ml/logistic_regression_binary": [
        "逻辑回归直接建模 `P(y|x)`，学习的是给定特征下类别的条件概率，而不是建模 `P(x|y)` 和 `P(y)`。因此它属于判别模型，关注决策边界而不是数据生成过程。",
        "线性回归通常最小化连续值预测的平方误差，输出不受概率范围约束。逻辑回归用 sigmoid 把线性打分映射成概率，并用 BCE 或极大似然训练分类边界。",
        "`BCE with logits` 可以把 sigmoid 和 log loss 合并成稳定公式，避免大正数或大负数 logits 下的溢出和 `log(0)`。分开算 sigmoid 后再 BCE，极端概率会让数值精度和梯度都更脆弱。",
        "阈值应该根据验证集上的 precision、recall、F1、PR 曲线或业务成本选择。比如漏报成本高就降低阈值提高 recall，误报成本高就提高阈值改善 precision。",
    ],
    "ml_dl_handwriting/01_classical_ml/logistic_regression_multiclass": [
        "softmax regression 一次性建模互斥多分类分布，所有类别概率共同归一化。one-vs-rest 会训练多个二分类器，类别之间不天然竞争，输出概率也不一定相互校准。",
        "softmax + cross entropy 对 logits 的梯度会化简为 `probs - onehot`。直觉上，模型给某类的概率高于目标就降低它，目标类概率低就提高它。",
        "可以在 cross entropy 中加入 class weight，让少数类或高成本类别的错误更重要。也可以重采样、使用 focal loss，或按业务指标调阈值，但要用验证集确认没有牺牲关键指标。",
        "softmax 输出不一定校准，它只是相对分数归一化后的结果，深度模型常会过度自信。可以用 temperature scaling、Platt scaling、isotonic regression 或校准集后处理。",
    ],
    "ml_dl_handwriting/01_classical_ml/naive_bayes_text": [
        "“朴素”指在给定类别后，特征之间被假设条件独立。这个假设在文本中显然不完全成立，但词频统计和类别之间的强相关信号很强，所以作为简单高偏差模型仍常有效。",
        "多项式 NB 建模词频或计数，适合 bag-of-words 文本分类。伯努利 NB 建模词是否出现，更适合二值特征，重复出现的次数不会像多项式模型那样增加证据。",
        "文本特征维度高，很多词概率很小，直接连乘会快速下溢到 0。转到 log 空间后，概率乘法变成 log 概率加法，数值更稳定，实现也更简单。",
        "alpha 太小会让未见词或低频词概率过低，模型对稀疏统计过敏。alpha 太大则会把分布过度拉平，削弱真实词频差异，模型变得欠拟合。",
    ],
    "ml_dl_handwriting/01_classical_ml/decision_tree_id3": [
        "ID3 用信息增益选择划分，C4.5 用增益率缓解多取值特征偏好，CART 通常用 Gini 做分类树并生成二叉树。CART 还能处理回归树，回归时常用平方误差或方差下降作为准则。",
        "多取值特征容易把样本切成很多小子集，甚至每个子集都很纯，从而得到很高的信息增益。问题是这种纯度可能只是记住样本 ID，泛化能力很差。",
        "防止过拟合可以限制最大深度、最小样本数、最小增益，或剪枝。预剪枝是在生长时提前停止，速度快但可能过早；后剪枝先长完整树再基于验证集或复杂度惩罚裁剪，通常更稳。",
        "entropy 来自信息论，越不纯信息量越大；Gini 可以理解为随机按类别分配时的错误概率。两者排序常相近，但 Gini 计算更简单，CART 中更常见。",
    ],
    "ml_dl_handwriting/01_classical_ml/dbscan_core": [
        "KMeans 假设用 K 个中心解释数据，需要预设簇数，并倾向球状簇。DBSCAN 基于密度连通，不需要预设 K，可以识别噪声和非凸形状簇。",
        "只要核心点之间能通过 eps 邻域链式连接，DBSCAN 就能把它们扩展成同一簇，所以不要求簇是球形。低密度区域无法连接到任何核心点，就会被标记为噪声或边界外样本。",
        "eps 通常结合距离分布或 k-distance 曲线选择，寻找从密集到稀疏的拐点。min_samples 可根据维度和噪声水平设定，维度越高或噪声越多通常需要更谨慎调参。",
        "DBSCAN 的簇定义依赖训练集中的密度连通结构，而不是学习一个显式参数化边界。新样本来了以后，它可能改变局部密度关系，所以原始算法没有像 KMeans 那样天然的 `predict`。",
    ],
    "ml_dl_handwriting/01_classical_ml/em_gmm_one_step": [
        "EM 通过构造当前参数下的后验责任度，优化似然的一个下界。E-step 固定参数更新下界，M-step 最大化下界，因此每轮不会降低原始数据似然。",
        "GMM 是软聚类，每个样本对每个高斯都有责任度；KMeans 是硬分配，只属于最近中心。若协方差相同且趋近很小，GMM 的责任度会接近 one-hot，表现就很像 KMeans。",
        "full covariance 可以表达任意椭圆形簇，但参数多、计算贵；diag 只建模各维独立方差，成本较低；spherical 每个簇只有一个方差，更接近球状簇假设。",
        "EM 对初始化敏感，因为似然目标非凸，可能收敛到局部最优或奇异解。常见缓解方式是多次随机初始化、用 KMeans 初始化均值、给协方差加正则和设置最小方差。",
    ],
    "ml_dl_handwriting/01_classical_ml/svm_hinge_loss": [
        "margin 是样本到决策超平面的带符号距离乘以标签，表示分类不仅要对，还要离边界足够远。最大化 margin 可以得到更稳健的决策边界，这是 SVM 泛化直觉的核心。",
        "hinge loss 在 margin 大于 1 后损失为 0，只关注分类错误或离边界不够远的样本。logistic loss 对所有样本都有非零惩罚，并输出概率意义更强，但没有硬间隔的几何解释那么直接。",
        "C 越大，模型越重视训练误分类，间隔可能变窄，过拟合风险更高。C 越小，模型更强调大间隔和正则化，允许更多训练错误，偏差可能更大。",
        "核 SVM 需要维护样本之间的核矩阵或大量支持向量，训练复杂度和存储都会随样本数快速增长。大样本下预测也可能慢，因为每次预测要和许多支持向量计算核函数。",
    ],
    "ml_dl_handwriting/02_dl_basics/mlp_forward": [
        "如果没有非线性，多层线性变换的复合仍然是一个线性变换，无法表达非线性决策边界。激活函数给网络引入分段线性或非线性结构，才让深层模型有更强表达能力。",
        "多层线性层不加激活等价于一个单独的线性层，因为矩阵乘法可以合并。无论堆多少层，它的函数族仍是线性或仿射变换。",
        "隐藏层越宽，通常可表达的函数越复杂，欠拟合风险降低。宽度过大且数据不足时，模型可能记忆训练集，因此需要正则化、早停、dropout 或更多数据来控制泛化。",
        "至少要缓存输入 X、第一层线性输出 z1、激活 h，以及可能的参数引用。backward 需要这些中间值计算 ReLU mask、权重梯度和传回上一层的梯度。",
    ],
    "ml_dl_handwriting/02_dl_basics/mlp_backward": [
        "softmax + cross entropy 时，最后一层 logits 的梯度可以直接写成 `probs - onehot`，再按 batch 或 token 平均。这样不用显式写 softmax 的完整雅可比矩阵，数值和实现都更稳定。",
        "没有激活函数时，整个网络只是线性层的复合，forward 等价于一个线性模型。backward 仍然能算，但训练再深也不会增加非线性表达能力，只会让参数冗余和优化更复杂。",
        "梯度消失常出现在深层链式乘法中，尤其是 sigmoid/tanh 饱和区或不合适初始化下。梯度爆炸也来自多层雅可比连乘，RNN、深层网络或学习率过大时更明显。",
        "数值梯度检查用有限差分近似某个参数的导数，再和解析梯度比较相对误差。检查时要用小网络、固定随机种子、关闭 dropout，并选择合适 epsilon，避免浮点误差主导。",
    ],
    "ml_dl_handwriting/02_dl_basics/relu_sigmoid_tanh": [
        "ReLU 在正区间导数为 1，不像 sigmoid/tanh 在大幅度输入时导数接近 0，所以能缓解饱和导致的梯度消失。缺点是负区间梯度为 0，学习率过大或偏置不当时神经元可能死亡。",
        "sigmoid 输出在 0 到 1，适合概率门控，但两端饱和且非零中心。tanh 输出在 -1 到 1，零中心但仍会饱和；ReLU 输出非负，计算简单，正区间梯度稳定，但可能 dead ReLU。",
        "dead ReLU 指神经元长期落在负半轴，输出和梯度都为 0，几乎不再更新。可以用较小学习率、合适初始化、Leaky ReLU、PReLU 或调整归一化来缓解。",
        "GELU 和 SiLU 都是平滑激活，允许输入按大小连续地通过，而不是像 ReLU 一刀切。它们在 Transformer/LLM 中常表现更好，直觉上提供了更柔和的数据依赖门控。",
    ],
    "ml_dl_handwriting/02_dl_basics/batch_norm_forward": [
        "训练时 BN 使用当前 mini-batch 的均值和方差，并更新 running mean/var。推理时不能依赖单个 batch 的统计量，而是使用训练期间累积的 running stats 保证输出稳定。",
        "BN 的统计量来自 batch 维，batch size 太小时均值和方差估计噪声很大。这样会让归一化本身引入随机扰动，导致训练不稳定或推理统计量不可靠。",
        "gamma 和 beta 让模型在归一化后仍能学习合适的尺度和平移。否则归一化会强行限制表示分布，可能削弱某些层需要保留的幅度信息。",
        "Transformer/LLM 的序列长度、batch 组成和自回归推理形态让 batch 统计不稳定，也不方便跨 token 使用。LayerNorm/RMSNorm 按样本内部维度归一化，不依赖 batch，更适合变长序列和小 batch 训练。",
    ],
    "ml_dl_handwriting/02_dl_basics/batch_norm_backward": [
        "关键链路是从 `y = gamma * x_hat + beta` 反传到 `x_hat`，再穿过标准化中的减均值、除标准差和方差计算。实现时最容易错的是 axis 和归一化分母，所以通常用紧凑公式或数值梯度校验。",
        "`beta` 是加到每个样本上的平移项，所以它的梯度就是上游梯度沿 batch 维求和。`gamma` 乘在 normalized input 上，因此梯度要累加 `dy * x_hat`。",
        "需要缓存 batch 均值、方差或 `inv_std`、normalized input、gamma，以及归一化时使用的 axis/eps。使用 forward 中同一批统计量很重要，否则 backward 和实际计算图不一致。",
        "batch size 小会让统计量估计噪声大，backward 中梯度也会受这批样本的均值方差强耦合影响。结果可能是 loss 抖动、收敛变慢，甚至 train/eval 分布不一致。",
    ],
    "ml_dl_handwriting/02_dl_basics/layer_norm_forward": [
        "BatchNorm 通常对 batch 维统计每个特征的均值方差，依赖同 batch 样本。LayerNorm 对每个样本内部的特征维统计，不依赖 batch 中其他样本。",
        "NLP/Transformer 中 batch size、序列长度和 padding 经常变化，batch 统计不稳定。LayerNorm 按 token 或样本自身归一化，训练和推理行为一致，更适合自回归和小 batch 场景。",
        "Post-LN 把 LayerNorm 放在残差之后，深层时梯度路径更容易不稳定。Pre-LN 把 LayerNorm 放在子层之前，让残差分支提供更直接的梯度通道，因此深层 Transformer 更容易训练。",
        "gamma/beta 不是数学上必须的，但它们提供可学习的尺度和平移，避免归一化过度限制表示。去掉后模型仍可运行，但表达灵活性和最终效果可能下降。",
    ],
    "ml_dl_handwriting/02_dl_basics/rms_norm_forward": [
        "RMSNorm 省掉了减均值，只计算平方均值的根并做缩放。相比 LayerNorm，它少了一步均值计算和 re-centering，计算和实现都更轻。",
        "很多 LLM 使用 RMSNorm，是因为它在效果接近 LayerNorm 的同时更简单、更快，并且适合大规模训练的数值稳定需求。它保留了对整体尺度的归一化，通常足够稳定残差流。",
        "RMSNorm 保留 re-scaling invariance：输入整体乘一个常数后，归一化方向基本不变。它失去了 re-centering invariance，因为不会减均值，输入整体平移会改变输出。",
        "eps 通常放在平方均值内部再开方，即 `sqrt(mean(x^2) + eps)`，避免 RMS 极小时除零。也有实现放在分母外，但要保持训练和推理一致，并注意数值尺度差异。",
    ],
    "ml_dl_handwriting/02_dl_basics/dropout_train_eval": [
        "Dropout 训练时随机屏蔽部分激活，迫使模型不能过度依赖某些神经元组合。它相当于训练许多子网络的近似集成，因此能降低共适应和过拟合。",
        "inverted dropout 在训练时除以 keep probability，让激活的期望保持不变。这样推理时可以直接使用完整网络，不需要再额外乘缩放系数，部署更简单。",
        "Dropout 会改变激活分布，而 BatchNorm 又依赖 batch 统计，两者顺序和强度不当可能让统计量变噪。实践中要谨慎调 dropout rate，现代架构里有时减少 BN 附近的 dropout。",
        "attention dropout 通常作用在 attention weights 上，随机弱化 token 间依赖。FFN dropout 作用在前馈层激活或输出上，主要正则化逐 token 的非线性变换。",
    ],
    "ml_dl_handwriting/02_dl_basics/adam_optimizer": [
        "SGD momentum 维护梯度的一阶动量，用历史方向平滑更新。Adam 同时维护一阶动量和二阶平方梯度，用二阶估计为每个参数自适应调整步长。",
        "训练初期 `m` 和 `v` 从 0 初始化，会系统性偏小。bias correction 用 `1 - beta^t` 修正这个偏差，否则前几步的有效更新尺度会不符合预期。",
        "传统 L2 正则把权重项加到梯度里，会被 Adam 的自适应二阶缩放影响，不再等价于简单权重衰减。AdamW 直接在参数更新中衰减权重，使正则强度更可控。",
        "Adam 对稀疏梯度和噪声梯度友好，因为每个参数有自适应学习率，少更新参数也能获得较大有效步长。风险是有时泛化不如 SGD，学习率、weight decay 和 beta 设置不当也会导致训练后期不稳。",
    ],
    "ml_dl_handwriting/03_attention_transformer/scaled_dot_product_attention": [
        "如果 Q 和 K 的各维独立且方差相近，点积的方差会随 `d_k` 增大而增大。除以 `sqrt(d_k)` 可以稳定 logits 尺度，避免 softmax 太早饱和导致梯度变小。",
        "causal mask 防止当前位置看到未来 token，是自回归生成的因果约束。padding mask 屏蔽补齐位置，避免模型把 pad token 当作真实上下文参与注意力。",
        "标准 attention 的 score 矩阵大小是 `seq_len^2`，所以时间复杂度和显存复杂度都近似 `O(n^2)`。多头和 batch 会再乘上对应维度，因此长上下文下瓶颈非常明显。",
        "softmax 前加一个很大的负数，会让对应位置的指数接近 0，从而概率接近 0。这样剩余未屏蔽位置仍能正常归一化，概率和保持为 1。",
    ],
    "ml_dl_handwriting/03_attention_transformer/self_attention": [
        "self-attention 需要计算序列内任意 token 两两交互，score 矩阵是 `n x n`。因此时间和显存随序列长度大致二次增长，这是长上下文 Transformer 的核心瓶颈。",
        "self-attention 不像 RNN 那样必须按时间步递推，Q/K/V 可以对所有位置一次性投影。只要 mask 处理好，训练时每个位置的注意力计算可以并行完成。",
        "每个 token 可以直接对任意距离的 token 分配注意力权重，所以路径长度是常数级的。相比 RNN 需要逐步传播信息，self-attention 更容易建模远距离依赖。",
        "多头让不同子空间学习不同关系，比如局部、长程、语法或位置模式。单头即使维度很大，也只有一套注意力分布，多头提供了多组并行的对齐方式。",
    ],
    "ml_dl_handwriting/03_attention_transformer/cross_attention": [
        "encoder-decoder Transformer 中，decoder 的每一层通常先做 masked self-attention，再通过 cross-attention 读取 encoder 输出。机器翻译、摘要等 seq2seq 模型里，这一步负责把目标端生成和源端表示对齐。",
        "self-attention 的 Q/K/V 来自同一序列，建模序列内部关系。cross-attention 的 Q 来自当前查询序列，K/V 来自外部上下文，因此本质是“用 query 去检索 context”。",
        "在 RAG 中，cross-attention 可以让生成端按需读取检索文档表示；在多模态中，文本 query 可以读取图像或音频 token。直觉上它是一个可学习的软检索和信息融合模块。",
        "输出长度由 Q 的长度决定，因为每个 query 位置都会得到一个加权后的 value 表示。K/V 只决定可被读取的上下文范围和注意力分布的 key 维度。",
    ],
    "ml_dl_handwriting/03_attention_transformer/multi_head_attention": [
        "多头把表示拆到多个子空间，每个头学习一套注意力模式，最后再拼接融合。单头大维度虽然容量大，但只有一张注意力图，多头能并行表达多种关系。",
        "标准 MHA 中 Q/K/V 投影各有 `d_model * d_model` 参数，输出投影也有 `d_model * d_model`，总量约 `4 * d_model^2`，不含 bias。num_heads 改变的是拆分方式，通常不改变总投影参数量。",
        "`head_dim = d_model / num_heads` 可以让拼接后维度回到 `d_model`，同时保持总计算量可控。这样增加头数主要改变注意力分解粒度，而不是线性增大 hidden 宽度。",
        "推理时主要瓶颈是 attention 读写 KV cache 的显存带宽，以及长上下文下的 QK 计算。batch、层数、head 数和序列长度都会放大这个成本。",
    ],
    "ml_dl_handwriting/03_attention_transformer/mha_with_mask": [
        "causal mask 屏蔽未来位置，用于保证自回归生成不能偷看答案。padding mask 屏蔽补齐 token，用于避免变长 batch 中的无效位置参与注意力。",
        "训练时通常一次性给完整序列加 causal mask，并行计算所有位置的 loss。自回归推理时每步只生成一个新 token，并通过 KV cache 复用历史 K/V，mask 逻辑更多体现为 position offset 和可见历史。",
        "mask 放在 softmax 前，屏蔽位置的概率会在归一化时变成接近 0，同时剩余位置概率和仍为 1。若 softmax 后再 mask，会破坏概率分布，并改变输出尺度。",
        "一整行都被 mask 时，softmax 的输入可能全是负无穷，结果会产生 NaN。工程上需要避免这种样本，或对全 mask 行做特殊处理，比如输出全 0 并跳过对应 loss。",
    ],
    "ml_dl_handwriting/03_attention_transformer/sinusoidal_position_encoding": [
        "attention 本身对 token 顺序近似置换不敏感，只知道内容相似度，不知道位置先后。位置编码给每个位置注入可区分信号，让模型能利用顺序和距离信息。",
        "不同频率让位置在多个尺度上被编码，低频捕捉长距离变化，高频捕捉局部位置差异。类似用一组基函数表示位置，使模型更容易组合出相对距离模式。",
        "绝对位置编码直接给每个位置一个向量，可学习版本灵活但外推弱。RoPE 把位置信息注入 Q/K 的旋转中，让 attention score 更自然地依赖相对位置；ALiBi 则直接给距离加线性偏置。",
        "正弦位置编码的公式可以为训练外的新位置继续计算，不依赖固定长度的参数表。它不保证外推一定好，但比固定可学习表更具备形式上的长度扩展能力。",
    ],
    "ml_dl_handwriting/03_attention_transformer/rope_apply": [
        "RoPE 对 Q/K 的成对维度按位置角度旋转，两个位置的内积会自然包含相对位置差。也就是说，attention score 不只看内容相似度，还能感知 query 和 key 的位置间隔。",
        "绝对位置编码通常是把位置向量加到 token embedding 上，位置信息混在输入表示里。RoPE 不直接加向量，而是在注意力计算前旋转 Q/K，使相对位置信息进入点积。",
        "KV cache 推理时，新 token 的 position 不能从 0 重新开始，而要接在已缓存长度之后。否则新 Q 和旧 K 使用的位置坐标不一致，attention 的相对位置会错乱。",
        "RoPE 用旋转让点积编码相对位置，属于乘性或几何式位置注入。ALiBi 直接按距离给 attention logits 加负偏置，鼓励近处更高权重，结构更简单且外推直觉更直接。",
    ],
    "ml_dl_handwriting/03_attention_transformer/gqa_mqa_shapes": [
        "MHA 每个 Q head 都有自己的 K/V head，KV cache 最大；MQA 所有 Q head 共享一组 K/V，cache 最小；GQA 让一组 Q heads 共享一组 K/V，是两者折中。cache 大小近似随 `n_kv_heads` 线性变化。",
        "自回归推理每生成一个 token，都要读取所有历史层的 K/V。长上下文和大 batch 下，KV cache 会占用大量显存，并且读取带宽会成为主要瓶颈。",
        "MQA 共享 K/V 会减少不同 head 的信息多样性，可能带来质量下降。GQA 保留多组 K/V，让多个 Q head 分组共享，在显存、带宽和质量之间折中。",
        "`repeat_kv` 是把少量 K/V head 在运行时复制或广播给多个 Q head，本质参数仍少。直接学习更多 K/V head 会增加参数和 cache，但每个 Q head 或组能拥有更独立的 key/value 表示。",
    ],
    "ml_dl_handwriting/03_attention_transformer/ffn_relu_gelu": [
        "Transformer 中 FFN 往往占很大参数比例，因为它包含从 `d_model` 到更大 hidden size 再回到 `d_model` 的两层线性变换。常见 expansion ratio 为 4 时，FFN 参数量通常超过 attention 投影。",
        "FFN 对每个 token 独立应用同一组线性层和激活，不依赖其他 token。token 间信息交换已经由 attention 完成，所以 FFN 可以在序列维上完全并行。",
        "GELU 是平滑的概率式门控，输入越大通过越多，输入较小时被柔和抑制。相比 ReLU 的硬截断，它在 Transformer 中常带来更平滑的优化和更好的表达。",
        "`4 * d_model` 是经验上兼顾容量和计算的宽度设置，给逐 token 非线性变换足够的中间维度。现代 LLM 使用 SwiGLU 等门控 FFN 时，hidden size 常会调整到约 `8/3 * d_model` 以控制参数量。",
    ],
    "ml_dl_handwriting/03_attention_transformer/swiglu": [
        "GLU 用一个 sigmoid gate 控制另一个线性分支，GeGLU 把 gate 激活换成 GELU，SwiGLU 换成 SiLU。它们共同点是用门控机制做通道筛选，差别在 gate 的非线性形式。",
        "gated FFN 能根据输入动态调节哪些通道被放大或抑制，比普通激活更像数据依赖的特征选择。现代 LLM 追求更强表达和稳定训练，因此常用 SwiGLU/GeGLU 替代 ReLU/GELU FFN。",
        "SwiGLU 通常有 gate projection、up projection 和 down projection 三组线性层，而普通 FFN 只有 up 和 down 两组。为了让参数量接近普通 FFN，SwiGLU 的中间维度常会设得小一些。",
        "SiLU gate 的值由输入本身决定，并且是连续平滑的缩放因子。它不是简单保留或丢弃通道，而是按样本内容动态调整每个隐藏通道的贡献。",
    ],
    "ml_dl_handwriting/04_llm_training_alignment/causal_lm_loss": [
        "causal LM 在位置 t 的隐藏状态只能预测下一个 token `x_{t+1}`，所以 logits 和 labels 要错开一位。若不 shift，就会变成用当前位置预测自己，训练目标不符合自回归生成。",
        "perplexity 等于按 token 平均 cross entropy 的指数，即 `PPL = exp(CE)`。CE 越低，模型给真实下一个 token 的平均概率越高，PPL 也越低。",
        "pad token 是为了 batch 对齐添加的，不是真实文本内容。把它计入 loss 会让模型学习预测 padding，并且不同样本长度会不公平地影响训练目标。",
        "SFT 的目标通常是让模型在给定 prompt 后生成高质量 answer，而不是复述 prompt。只对 answer token 计 loss，可以把监督信号集中在助手回复上，避免用户输入本身污染训练。",
    ],
    "ml_dl_handwriting/04_llm_training_alignment/sft_label_mask": [
        "SFT 训练的是在 prompt 条件下生成 answer 的能力，prompt 是条件，不是要模型学习输出的目标。只训练 answer token 可以避免模型被奖励去复述用户问题或 system 指令。",
        "多轮对话中通常只让 assistant 回复位置参与 loss，system/user token 和 padding 都设为 ignore。若要训练特定轮次，也要严格根据 chat template 标记每段角色边界。",
        "prompt token 也计入 loss 会让模型优化“预测用户输入”的概率，而这不是部署时的生成任务。它还会让长 prompt 样本贡献过多 loss，稀释 answer 部分的监督信号。",
        "chat template 决定 system/user/assistant 的特殊 token、分隔符和起止位置。模板不同会改变 answer 从哪里开始、哪些 token 属于角色标记，因此 label mask 边界必须和模板一致。",
    ],
    "ml_dl_handwriting/04_llm_training_alignment/preference_pair_format": [
        "SFT 数据通常是单个 prompt 对应一个示范答案，用最大似然学习“模仿这个答案”。DPO 数据是同一 prompt 下的 chosen/rejected 成对偏好，用相对 logprob 学习更偏向 chosen。",
        "构造时要保证 chosen 和 rejected 回答同一个 prompt，并且偏好标签可靠。清洗时要去掉顺序反转、模板不一致、重复样本、过短无效回答和明显长度偏置过强的样本。",
        "共享 prompt 才能把比较焦点放在回答质量上，而不是不同问题本身的难度差异。若 prompt 不同，chosen/rejected 的 logprob 差就混入了条件差异，偏好信号不再干净。",
        "如果 chosen 系统性更长或更短，用 sum logprob 会偏向长度相关的概率差异，而不一定是质量差异。常见处理包括只比较 answer token、检查长度分布、使用 mean logprob 或做长度分桶分析。",
    ],
    "ml_dl_handwriting/04_llm_training_alignment/dpo_loss": [
        "PPO/RLHF 通常先训练 reward model，再用强化学习优化策略，并需要采样和 KL 约束。DPO 直接用偏好对构造分类式目标优化语言模型，流程更简单，不显式训练 reward model。",
        "reference model 提供一个基准偏好 margin，约束当前模型不要为了迎合偏好数据而偏离原模型太多。它相当于隐式 KL 约束的一部分，帮助保留原有语言能力和稳定训练。",
        "beta 控制偏好 margin 的放大程度，也影响相对 reference 的约束强度。beta 太大时更新更激进，可能过拟合偏好；太小时信号变弱，模型变化不明显。",
        "DPO 从 RLHF 的最优策略形式出发，把 reward 差转化为策略和 reference 的 logprob 差。这样可以直接用 chosen/rejected 偏好优化模型，而不需要单独拟合一个显式 reward 函数。",
    ],
    "ml_dl_handwriting/04_llm_training_alignment/reward_pairwise_loss": [
        "偏好标注通常只可靠地表达“哪个回答更好”，不一定给出可比较的绝对分数。pairwise loss 学习的是 reward 差值，只要 chosen 分数高于 rejected 就符合监督信号。",
        "pointwise loss 给单个样本拟合绝对标签或分数，pairwise loss 比较一对样本的相对顺序。listwise loss 一次考虑一个列表的整体排序，信息更丰富但数据和实现更复杂。",
        "reward 的绝对值通常没有稳定语义，因为加一个常数不改变 pairwise 偏好概率。更重要的是同一 prompt 或同一分布下的相对排序，以及分数尺度在后续 RL 中是否稳定。",
        "在 PPO/RLHF 中，reward model 给模型生成的回答打分，作为强化学习的奖励信号。训练策略时通常还会加入 KL 惩罚，避免模型为了高 reward 偏离参考模型太远。",
    ],
    "ml_dl_handwriting/04_llm_training_alignment/contrastive_loss": [
        "InfoNCE 可以看成一个 cross entropy：给定 query，要在一个正样本和多个负样本中分类出正确 key。分子是正样本 logit，分母是所有候选 logit 的 softmax 归一化。",
        "in-batch negatives 指一个 batch 中其他样本的 key 被当作当前 query 的负样本。优点是不用额外采样就能得到很多负例，缺点是 batch 内可能存在语义相近的 false negative。",
        "temperature 越小，softmax 越尖锐，模型更关注难负样本，但梯度也可能更不稳定。temperature 越大，分布更平滑，训练信号更温和，但区分压力可能不足。",
        "normalize 后点积等价于 cosine similarity，训练更关注方向而不是向量范数。这样可以避免模型通过单纯放大 embedding 范数来提高相似度，使表示空间更稳定。",
    ],
}
